#!/usr/bin/env bash

INSTALL_DIR=~

# Reset color
Color_Off='\033[0m'
# Colors
Black='\033[0;90m'
Red='\033[0;91m'
Green='\033[0;92m'
Yellow='\033[0;93m'
Blue='\033[0;94m'
Purple='\033[0;95m'
Cyan='\033[0;96m'
White='\033[0;97m'
# Bold colors
BBlack='\033[1;30m'
BRed='\033[1;31m'
BGreen='\033[1;32m'
BYellow='\033[1;33m'
BBlue='\033[1;34m'
BPurple='\033[1;35m'
BCyan='\033[1;36m'
BWhite='\033[1;37m'


# Creates confirm prompt
#
# @param text Text to display in prompt
# @return     True if user confirmed, otherwise false
confirm() {
  local message=$1

  echo -n -e "${BWhite}$message${Color_Off} [Y/n] "
  read response
  case $response in
    [yY][eE][sS]|[yY]|"")
      true
      ;;
    *)
      false
      ;;
  esac
}

# Prints a message to user
#
# @param text Text to print
log() {
  local text=$1
  echo -e "${BWhite}:: $text${Color_Off}"
}


w_prepare() {
  log "Creating folders..."
  mkdir -p $INSTALL_DIR/.vim/{bundle,backup,tmp,undo,sessions,spell,view}
}

w_download_plugin_manager() {
  log "Downloading plugin manager..."
  curl -fLo ~/.vim/autoload/plug.vim --create-dirs https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
}

w_copy_configs() {
  log "Copying configs..."
  cp vimrc $INSTALL_DIR/.vimrc
  cp gvimrc $INSTALL_DIR/.gvimrc
  cp -r reovim $INSTALL_DIR/.vim/
  if [[ ! -f $INSTALL_DIR/.vimrc.user.before ]]; then
    cp vimrc.user.before $INSTALL_DIR/.vimrc.user.before
    echo
    if confirm "Use heavy version of config by default?"; then
      { echo; echo "let g:reovimrc_light = 0"; } >> $INSTALL_DIR/.vimrc.user.before
    fi
  fi
  if [[ ! -f $INSTALL_DIR/.vimrc.user.install ]]; then
    cp vimrc.user.install $INSTALL_DIR/.vimrc.user.install
  fi
  if [[ ! -f $INSTALL_DIR/.vimrc.user.after ]]; then
    cp vimrc.user.after $INSTALL_DIR/.vimrc.user.after
  fi
  if [[ ! -f $INSTALL_DIR/.gtkrc-2.0.mine ]]; then
    cp gtkrc-2.0.mine $INSTALL_DIR/.gtkrc-2.0.mine
  fi
  if [[ ! -f $INSTALL_DIR/.gtkrc-2.0 ]]; then
    cp gtkrc-2.0.mine $INSTALL_DIR/.gtkrc-2.0
  fi
}

w_install_plugins() {
  log "Installing plugins..."
  REOVIMRC_LIGHT=0 vim -c ":PlugUpdate | :qa!"
  REOVIMRC_LIGHT=1 vim -c ":PlugUpdate | :qa!"
}

w_say_goodbye() {
  echo
  echo -e "${BWhite}Advice:${Color_Off}"
  echo "You can set these aliases to launch either light or full-featured version of vim:"
  echo "alias lvim=\"env REOVIMRC_LIGHT=1 vim\""
  echo "alias hvim=\"env REOVIMRC_LIGHT=0 vim\""
  echo
  echo -e "${Green}~~~ Happy coding with vim! ~~~${Color_Off}"
}


main() {
  w_prepare
  w_download_plugin_manager
  w_copy_configs
  w_install_plugins
  w_say_goodbye
}

[[ "$0" == "$BASH_SOURCE" ]] && main $@
